# Generated by Django 3.2.9 on 2022-05-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='animal_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='przychodnia.animal'),
            preserve_default=False,
        ),
    ]
