# Generated by Django 4.0.4 on 2022-05-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0004_rename_animal_key_bill_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
