# Generated by Django 4.0.4 on 2022-05-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0008_alter_bill_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przychodnia.animal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przychodnia.owner')),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
