# Generated by Django 4.0.4 on 2022-06-03 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0010_vet_alter_animal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltreatment',
            name='vet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przychodnia.vet'),
        ),
    ]
